version: 3

includes:
  terraform:
    taskfile: ./TaskTerraform.yml
    dir: ./deployment
    flatten: true
    vars:
      TFLINT_CONFIG: ../.tflint.hcl


tasks:
  build:
    env:
    cmd: go build main.go

  app:up:
    desc: Compose up
    cmds:
      - docker compose up -d
  app:down:
    desc: Compose down
    cmds:
      - docker compose down

  ssh:
    desc: Connect to instance via ssh
    cmds:
      - ssh -i "~/terraform.pem" ec2-user@ec2-13-60-222-206.eu-north-1.compute.amazonaws.com
