version: 3

includes:
  terraform:
    taskfile: ./TaskTerraform.yml
    dir: ./deployment
    flatten: true
    vars:
      TFLINT_CONFIG: .tflint.hcl


tasks:
  app:up:
    desc: Compose up
    cmds:
      - docker compose up -d
  app:down:
    desc: Compose down
    cmds:
      - docker compose down
